import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'ta' | 'hi';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    // Navigation & Menu
    dashboard: 'Dashboard',
    myPosts: 'My Posts',
    matches: 'Matches',
    notifications: 'Notifications',
    settings: 'Settings',
    logout: 'Logout',
    
    // Dashboard
    todayImpact: "Today's Impact",
    weeklyImpact: 'Weekly Impact Trend',
    mealsDistributed: 'Meals Distributed',
    co2Prevented: 'CO₂ Prevented (kg)',
    waterSaved: 'Water Saved (L)',
    emergencyAlerts: 'Emergency Alerts',
    thisMonth: 'This Month',
    mealsSaved: 'meals saved',
    foodDiverted: 'food diverted',
    co2Prevented2: 'CO₂ prevented',
    
    // Food Cards
    quantity: 'Quantity',
    expiry: 'Expiry',
    distance: 'Distance',
    freshness: 'Freshness',
    requestFood: 'Request This Food',
    availableFood: "Today's Available Food",
    recommendedForYou: 'Recommended for you',
    seeAll: 'See all',
    
    // Search & Filter
    search: 'Search',
    searchFood: 'Search for surplus food...',
    groceries: 'Groceries',
    meals: 'Meals',
    bakedGoods: 'Baked Goods',
    listView: 'List View',
    mapView: 'Map View',
    
    // Settings
    userDetails: 'User Details',
    darkMode: 'Dark Mode',
    language: 'Language',
    chooseLanguage: 'Which language would you like to use?',
    chooseLanguageSubtitle: 'Select your preferred language for the website.',
    changeLanguage: 'Change language',
    english: 'English',
    tamil: 'Tamil',
    hindi: 'Hindi',
    email: 'Email',
    password: 'Password',
    phone: 'Phone',
    location: 'Location',
    role: 'Role',
    name: 'Name',
    address: 'Address',
    preferences: 'Preferences',
    restaurant: 'Restaurant',
    volunteer: 'Volunteer',
    organizationInfo: 'Organization Information',
    orgName: 'Organization Name',
    orgType: 'Organization Type',
    license: 'License/Registration Number',
    website: 'Website',
    registrationDate: 'Registration Date',
    donationStats: 'Donation Statistics',
    totalDonations: 'Total Donations',
    mealsContributed: 'Meals Contributed',
    moneyValue: 'Estimated Value',
    impactContribution: 'Your Impact Contribution',
    saved: 'Settings saved successfully!',
    
    // Features (for hamburger menu)
    oneClickPosting: 'One-Click Surplus Posting',
    smartMatching: 'Smart NGO Matching',
    foodSafety: 'Food Safety Timer',
    photoVerification: 'Photo Verification (AI)',
    demandAware: 'Demand-Aware Redistribution',
    falsePrevention: 'False Surplus Prevention',
    heatmap: 'Live Food Rescue Heatmap',
    impactMeter: 'Carbon & Climate Impact',
    emergencyMode: 'Emergency Hunger Mode',
    accessibility: 'Settings & Accessibility',
    
    // Buttons
    enable: 'Enable',
    disable: 'Disable',
    save: 'Save Changes',
    cancel: 'Cancel',
    
    // Messages
    welcomeBack: 'Welcome back!',
    goodMorning: 'Good Morning',
    letsSaveFood: "Let's save some yummy food...",
    urgentNeed: 'Urgent: 50+ people need meals NOW',
    locationAway: 'away',
    respondNow: 'Respond Now',

    backToDashboard: 'Back to Dashboard',
    postSurplusFood: 'Post Surplus Food',
    freshCheck: 'Fresh Check',
    details: 'Details',
    review: 'Review',
    success: 'Success',
    reviewYourPost: 'Review Your Post',
    foodName: 'Food Name',
    quantityServings: 'Quantity (servings)',
    safetyWindow: 'Safety Window',
    temperatureRange: 'Temperature Range',
    availableFor: 'Available For',
    qualityScore: 'Quality Score',
    notSpecified: 'Not specified',
    confirmAndPost: 'Confirm & Post',
    posting: 'Posting…',
    failedToPostFood: 'Failed to post food. Please try again.',
    numberOfServings: 'Number of servings',
    minTemp: 'Min temp',
    maxTemp: 'Max temp',
    enterPickupAddress: 'Enter complete pickup address',
    specialInstructions: 'Any special instructions or details about the food',
    signIn: 'Sign in',
    signUp: 'Sign up',
    createAccount: 'Create account',
    createAccountSubtitle: 'Create your account to get started',
    creatingAccount: 'Creating account…',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    backToSignIn: 'Back to Sign in',
    fullNameRequired: 'Full name is required',
    fullNameMinLength: 'Name must be at least 2 characters',
    emailRequired: 'Email is required',
    invalidEmail: 'Please enter a valid email address',
    passwordRequired: 'Password is required',
    passwordMinLength: 'Password must be at least 8 characters',
    confirmPassword: 'Confirm Password',
    passwordsDoNotMatch: 'Passwords do not match',
    registrationFailed: 'Registration failed. Please try again.',
    enterYourName: 'Your full name',
    personalDetails: 'Personal details',
    personalDetailsSubtitle: 'Add your contact details so organisations can reach you (optional).',
    optional: 'Optional',
    enterPhone: 'e.g. +91 98765 43210',
    enterAddress: 'City, area, or full address',
    skip: 'Skip',
    saveAndContinue: 'Save & Continue',
    saving: 'Saving…',
    saveFailed: 'Failed to save. Please try again.',
    emailPlaceholder: 'Email',
    passwordPlaceholder: 'Password',
    rememberMe: 'Remember me',
    browseWithoutSignIn: 'Browse without signing in',
    backToFreshCheck: 'Back to Fresh Check',
    continueToReview: 'Continue to Review',
    safetyWindowMinutes: 'Safety Window (Minutes)',
    storageTempRange: 'Storage Temperature Range (°C)',
    availableForHours: 'Available For (Hours)',
    locationName: 'Location Name',
    fullAddress: 'Full Address',
    additionalNotes: 'Additional Notes',
    editDetails: 'Edit Details',
    goToDashboard: 'Go to Dashboard',
    postAnother: 'Post Another',
    foodPostedSuccess: 'Food Posted Successfully!',
    foodPostedSuccessDesc: 'Your surplus food has been posted and is now available for NGOs to request. Matched NGOs will be notified shortly.',
    min: 'Min',
    max: 'Max',
    back: 'Back',
    signInWithEmailPassword: 'Sign in with your email and password',
    enterYourEmail: 'Enter your email',
    enterYourPassword: 'Enter your password',
    signingIn: 'Signing in…',
    browseSiteWithoutSignIn: 'Browse site without signing in',
    staySignedIn: 'Stay signed in on this device.',
    signOutWhenClose: 'Sign out when you close the browser.',

    // Dashboard home & nav
    welcome: 'Welcome back!',
    welcomeBackWithName: 'Welcome back, {{name}}!',
    missionToday: "Here's what's happening with your food rescue mission today",
    storageTemperature: 'Storage Temperature',
    hours: 'hours',
    equivalent: 'equivalent',
    matchedStatus: 'MATCHED',
    acceptedStatus: 'ACCEPTED',
    deliveredStatus: 'DELIVERED',
    pickedUpStatus: 'PICKED_UP',
    makingADifference: "You're making a difference. Keep delivering impact!",
    postSurplus: 'Post Surplus',
    myMatches: 'My Matches',
    impact: 'Impact',
    weeklyTrend: 'Weekly Impact Trend',
    foodSafetyTimer: 'Food Safety Timer',
    liveDeliveryTrack: 'Live Delivery Track',
    carbonSaved: 'Carbon Saved',
    verification: 'Verification',
    features: 'Features',
    donor: 'Donor',
    freshnessChecker: 'Freshness Food Checker',
    donating: 'Donating',
    ngo: 'NGO',
    report: 'Report',
    aboutUs: 'About Us',
    quickActions: 'Quick Actions',
    recentActivity: "Today's Activity",
    pendingMatches: 'Pending Matches',
    activeDeliveries: 'Active Deliveries',
    didYouKnow: 'Did you know?',
    tipText: 'Every 1 kg of food rescued saves ~2.5 kg CO₂ and helps feed someone in need.',
    neededFoodMap: 'Needed food areas',
    howYouCanHelp: 'How you can help',
    postFoodNow: 'Post food now',
    viewMatches: 'View matches',
    seeImpact: 'See impact',
    adminOrg: 'Admin / Organisation',
    profile: 'Profile',
    goToSettings: 'Go to Settings',
    postsMatchedToday: 'posts matched with NGOs today',
    deliveryCompleted: 'delivery completed',
    matchAwaiting: 'match awaiting your response',
    getStartedNow: 'Get started now',
    thisWeek: 'This Week',
    thisYear: 'This Year',
    keyInsights: 'Key Insights',
    periodComparison: 'Period Comparison',
    lastWeek: 'Last Week',
    lastMonth: 'Last Month',
    lastYear: 'Last Year',
    change: 'change',
    ofTotal: 'of total',
    yourMatches: 'Your Matches',
    seeWhichNGOs: 'See which NGOs are interested in your food',
    organization: 'Organization',
    donationValue: 'Donation Value',
    accept: 'Accept',
    decline: 'Decline',
    startTravel: 'Start travel',
    viewOnMap: 'View distance in maps',
    allMatches: 'All',
    matchPending: 'Pending',
    matchAccepted: 'Accepted',
    matchInDelivery: 'In delivery',
    matchCompleted: 'Completed',
    yourImpact: 'Your Impact',
    seeHowMuch: "See how much difference you're making",
    aboutResQMeal: 'About ResQ Meal',
    turningSurplus: 'Turning surplus into sustenance.',
    fullStackPlatform: 'ResQ Meal is a full-stack platform that connects donors, NGOs, and volunteers to redistribute surplus food—reducing waste and fighting hunger. Post food, get matched, track delivery, and see your impact.',
    ourMission: 'Our mission',
    missionText: 'To ensure good food reaches people, not landfills. We help restaurants and donors post surplus, match it with NGOs in need, and track delivery so every meal counts.',
    ourVision: 'Our vision',
    visionText: 'A world where surplus food is routinely rescued, shared, and measured—reducing hunger and environmental impact in every community we serve.',
    howItWorks: 'How it works',
    postSurplusDesc: 'Donors add surplus food with quantity, expiry, and optional AI freshness check.',
    getMatched: 'Get matched',
    getMatchedDesc: 'NGOs see relevant listings; our system suggests the best matches by need and distance.',
    confirmDeliver: 'Confirm & deliver',
    confirmDeliverDesc: 'Volunteers pick up and deliver. Track status and complete with proof of delivery.',
    seeImpactDesc: 'Meals saved, CO₂ prevented, and water saved are tracked and shown in your dashboard.',
    websiteFeatures: 'Website features & details',
    websiteFeaturesDesc: 'ResQ Meal includes the following features to support donors, NGOs, and volunteers:',
    technologyAI: 'Technology & AI',
    technologyAIText: 'The Fresh Food Checker uses optional ML models for quality and freshness: image-based (e.g. Bedrock/Claude Vision, TFLite, Roboflow YOLO, FreshVision, Food-101 classification) and environment-based (temperature, humidity, storage time). Food-Image-Recognition can classify dishes and return nutrition. All of this helps donors and NGOs trust that surplus food is safe to redistribute.',
    getInvolved: 'Get involved',
    getInvolvedText: 'Post surplus as a donor, request matches as an NGO, or sign up as a volunteer to deliver. Use the Dashboard, Donor, NGO, and Report sections to get started. For support or partnerships, reach out through your account or settings.',
    followUs: 'Follow us',
    // Elite Mode
    eliteMode: 'Elite Mode',
    eliteTitle: 'Elite Mode — Dignity for Elders',
    eliteSubtitle: 'For elders left in care homes by their children',
    eliteWho: 'Who is Elite Mode for?',
    eliteWhoDesc: 'Elders who were left in orphanages or care homes by their children. These parents often do not prefer regular donated surplus food; they eat from marriage and celebration food and from food ordered for them by their kids.',
    eliteWhat: 'What food do they eat?',
    eliteWhatDesc: 'Marriage and celebration food (from weddings and events), festival-made food, and food ordered by their children—not typical donated surplus. Elite Mode connects care homes and elders with these preferred sources.',
    eliteHow: 'How Elite Mode works',
    eliteHow1: 'Care homes or elders register for Elite Mode.',
    eliteHow2: 'Event caterers and families can list marriage/celebration food or place orders for parents in care.',
    eliteHow3: 'Food is delivered to registered care homes so elders get the food they prefer.',
    getInvolvedElite: 'Register your care home, list event food, or order food for a parent in care.',
    eliteFestivalTitle: 'Festival-made food',
    eliteFestivalDesc: 'Festival-made food is also served through ResQ Meal. Families and caterers can list surplus from festivals and celebrations; care homes receive it so elders enjoy the same special foods they grew up with.',
    eliteFestivalServed: 'Served on this website',
    eliteFestivalEx1: 'Diwali sweets & savouries',
    eliteFestivalEx2: 'Pongal / harvest festival specials',
    eliteFestivalEx3: 'Eid biryani & sweets',
    eliteFestivalEx4: 'Christmas cakes & treats',
    eliteFestivalEx5: 'Other festival & celebration dishes',
    eliteFestivalExamplesLabel: 'Examples served on this website:',
    eliteRegister: 'Register',
    eliteRegisterHome: 'Register your home',
    eliteRegisterHomeDesc: 'Add your home or care home address and list foods you have available. Click "View on map" to open maps and see distance.',
    eliteHomeAddress: 'Home address',
    eliteHomeAddressPlaceholder: 'Street, city, state, PIN',
    eliteFoodsAvailable: 'Foods available',
    eliteAddFood: 'Add food',
    eliteFoodName: 'Food name',
    eliteFoodType: 'Type (e.g. festival, celebration)',
    eliteQuantity: 'Quantity',
    eliteSubmitRegistration: 'Submit registration',
    eliteViewOnMap: 'View on map / Get directions',
    eliteMyRegistrations: 'My registrations',
    eliteBackToElite: 'Back to Elite Mode',
    eliteNoRegistrationsYet: 'No registrations yet. Register your home and list foods to get started.',
    eliteEstablishmentType: 'Type of establishment',
    eliteEstablishmentTypePlaceholder: 'e.g. Care home, Elder home, Individual',
    eliteContactName: 'Contact person name',
    eliteContactNamePlaceholder: 'Full name',
    eliteContactPhone: 'Contact phone',
    eliteContactPhonePlaceholder: 'Phone number',
    eliteResidentCount: 'Number of residents (optional)',
    eliteResidentCountPlaceholder: 'e.g. 10',
    elitePreferredFoodTypes: 'Preferred food types (wedding & special events)',
    elitePreferredWedding: 'Wedding / marriage food',
    elitePreferredFestival: 'Festival food',
    elitePreferredCelebration: 'Celebration / event food',
    eliteDietaryNotes: 'Dietary notes (optional)',
    eliteDietaryNotesPlaceholder: 'e.g. Vegetarian only, no nuts',
    eliteBrowseTitle: 'Available special event food',
    eliteBrowseDesc: 'Foods from weddings, festivals and celebrations. Click a card to see distance and get directions.',
    eliteDistanceAway: '{{km}} km away',
    eliteGetDirections: 'Get directions',
    eliteNoEliteFoodsYet: 'No special event food listed yet. Check back later or register to receive.',

    // Detailed Reports
    clickForDetails: 'Click for details',
    backToReport: 'Back to Report',
    detailedReport: 'Detailed Report',
    dailyBreakdown: 'Daily Breakdown',
    weeklyBreakdown: 'Weekly Breakdown',
    monthlyBreakdown: 'Monthly Breakdown',
    topSources: 'Top Sources',
    trendAnalysis: 'This chart shows the weekly trend with detailed data points for each day.',
    lastWeekSummary: 'Last week showed consistent performance with steady growth.',
    lastMonthSummary: 'Last month demonstrated strong growth with increasing impact each week.',
    lastYearSummary: 'Last year showed progressive improvement with consistent monthly growth.',

    // Organisation Report
    adminOrgReport: 'Organisation Report',
    freshFoodAnalyser: 'Fresh Food Analyser',
    postFood: 'Post Food',
    overallReport: 'Overall report',
    overallReportDesc: 'Summary of your organisation\'s impact and activity. Click a card for extended details.',
    peopleServed: 'People served',
    mealsDelivered: 'Meals delivered',
    deliveriesCompleted: 'Deliveries completed',
    activeVolunteers: 'Active volunteers',
    totalBeneficiaries: 'Total beneficiaries',
    successfulRuns: 'Successful runs',
    deliveries: 'Deliveries',
    volunteers: 'Volunteers',
    extendedBreakdown: 'extended breakdown',
    quarterToDate: 'Quarter to date',
    yearToDate: 'Year to date',
    topLocation: 'Top location',
    averagePerDelivery: 'Average per delivery',
    totalAllTime: 'Total all time',
    peakDayThisMonth: 'Peak day this month',
    onTimeRate: 'On-time rate',
    totalSuccessful: 'Total successful',
    avgDistancePerRun: 'Avg. distance per run',
    newThisMonth: 'New this month',
    completed5PlusDeliveries: 'Completed 5+ deliveries',
    topVolunteerDeliveries: 'Top volunteer (deliveries)',
    totalActive: 'Total active',
    retentionRate: 'Retention rate',
    equivalentEmissionsAvoided: 'Equivalent emissions avoided',
    equivalentCarKm: 'Equivalent car km',
    equivalentTrees1Year: 'Equivalent trees (1 year)',
    foodRescued: 'Food rescued',
    weightDivertedFromWaste: 'Weight diverted from waste',
    primaryCategory: 'Primary category',
    partnersInvolved: 'Partners involved',
    addFoodDonorsOnly: 'Add food (donors only)',
    addFoodDonorsDesc: 'As a donor, add food that needs pickup or delivery. Optionally check freshness first with our AI checker; then fill the form. It will appear on the volunteer page.',
    skipFillForm: 'Skip → Fill form',
    checkFreshnessFirstOptional: 'Check freshness first (optional)',
    foodNamePlaceholder: 'e.g. Rice and curry, Bread rolls',
    type: 'Type',
    foodType: 'Food type',
    servings: 'servings',
    servingsPlaceholder: 'e.g. 10',
    addressPickupLocation: 'Address / pickup location',
    addressPlaceholder: 'e.g. 123 Main St, Chennai',
    descriptionOptional: 'Description (optional)',
    descriptionPlaceholder: 'Any notes for volunteers',
    adding: 'Adding…',
    addFood: 'Add food',
    foodYouAddedVisibleToVolunteers: 'Food you added (visible to volunteers)',
    noFoodAddedYet: 'No food added yet.',
    foodNameAndAddressRequired: 'Food name and address are required.',
    foodAddedSuccess: 'Food added. It will appear on the volunteer page.',
    failedToAddFood: 'Failed to add food.',
    monthlyComparison: 'Monthly comparison',
    thisMonthMeals: 'This month (meals)',
    lastMonthMeals: 'Last month (meals)',
    vsLastMonth: 'vs last month',
    impactTrends: 'Impact trends',
    impactTrendsDesc: 'Monthly meals delivered and people served over the last 6 months.',
    overviewAllTime: 'Overview (all time)',
    keyMetricsComparison: 'Key metrics comparison',
    foodType_meals: 'Meals',
    foodType_vegetables: 'Vegetables',
    foodType_baked: 'Baked',
    foodType_dairy: 'Dairy',
    foodType_fruits: 'Fruits',
    foodType_others: 'Others',
    loading: 'Loading…',
    clearFreshnessResult: 'Clear freshness result',
    value: 'Value',
    
    // Volunteer Mode
    volunteerMode: 'Volunteer Mode',
    volunteerModeDescription: 'View available food from organisations and your assigned deliveries here.',
    availableFoodFromDonors: 'Available food from donors',
    availableFoodFromDonorsDesc: 'Food added by donors. Volunteers can view and check freshness only.',
    noFoodFromDonors: 'No food from donors right now.',
    noFoodFromDonorsDesc: 'When donors add food, it will appear here. You can check freshness for each item.',
    myDeliveries: 'My deliveries',
    noDeliveriesAssigned: 'No deliveries assigned yet.',
    noDeliveriesAssignedDesc: 'Your organisation will assign deliveries to you.',
    status: 'Status',
  },
  ta: {
    // Navigation & Menu
    dashboard: 'டாஷ்போர்டு',
    myPosts: 'என் பதிப்புகள்',
    matches: 'பொருந்தும் இடங்கள்',
    notifications: 'அறிவிப்புகள்',
    settings: 'அமைப்புகள்',
    logout: 'வெளியே வாருங்கள்',
    
    // Dashboard
    todayImpact: 'இன்றைய தாக்கம்',
    weeklyImpact: 'வாரவாரி தாக்கம் போக்கு',
    mealsDistributed: 'விநியோகிக்கப்பட்ட உணவு',
    co2Prevented: 'தடுக்கப்பட்ட CO₂ (கிகி)',
    waterSaved: 'சேமிக்கப்பட்ட நீர் (எல்)',
    emergencyAlerts: 'அவசர எச்சரிக்கைகள்',
    thisMonth: 'இந்த மாதம்',
    mealsSaved: 'உணவு சேமிக்கப்பட்டது',
    foodDiverted: 'நியமிக்கப்பட்ட உணவு',
    co2Prevented2: 'தடுக்கப்பட்ட CO₂',
    
    // Food Cards
    quantity: 'அளவு',
    expiry: 'முடிவதற்கான நேரம்',
    distance: 'தூரம்',
    freshness: 'புதுமை',
    requestFood: 'இந்த உணவைக் கோருங்கள்',
    availableFood: 'இன்றைய கிடைக்கும் உணவு',
    recommendedForYou: 'உங்களுக்கான பரிந்துரைப்பு',
    seeAll: 'அனைத்தையும் பார்க்கவும்',
    
    // Search & Filter
    search: 'தேடுங்கள்',
    searchFood: 'உதிரி உணவைத் தேடுங்கள்...',
    groceries: 'கடை பொருட்கள்',
    meals: 'உணவு',
    bakedGoods: 'சுட்ட பொருட்கள்',
    listView: 'பட்டியல் பார்வை',
    mapView: 'வரைபட பார்வை',
    
    // Settings
    userDetails: 'பயனர் விவரங்கள்',
    darkMode: 'இருண்ட முறை',
    language: 'மொழி',
    chooseLanguage: 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
    chooseLanguageSubtitle: 'தளத்திற்கு விரும்பிய மொழியைத் தேர்ந்தெடுக்கவும்.',
    changeLanguage: 'மொழியை மாற்று',
    english: 'ஆங்கிலம்',
    tamil: 'தமிழ்',
    hindi: 'இந்தி',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    phone: 'தொலைபேசி',
    location: 'இடம்',
    role: 'பங்கு',
    name: 'பெயர்',
    address: 'முகவரி',
    preferences: 'விருப்பங்கள்',
    restaurant: 'உணவகம்',
    volunteer: 'தன்னார்வலர்',
    organizationInfo: 'நிறுவன தகவல்',
    orgName: 'நிறுவன பெயர்',
    orgType: 'நிறுவன வகை',
    license: 'உரிமம்/பதிவு எண்',
    website: 'வலைத்தளம்',
    registrationDate: 'பதிவு தேதி',
    donationStats: 'நன்கொடை புள்ளியியல்',
    totalDonations: 'மொத்த நன்கொடைகள்',
    mealsContributed: 'பங்களிக்கப்பட்ட உணவு',
    moneyValue: 'மதிப்பிடப்பட்ட மதிப்பு',
    impactContribution: 'உங்கள் தாக்கம் பங்களிப்பு',
    saved: 'அமைப்புகள் வெற்றிகரமாக சேமிக்கப்பட்டது!',
    
    // Features (for hamburger menu)
    oneClickPosting: 'ஒரு கிளிக் உணவு பதிவு',
    smartMatching: 'ஸ்மார்ட் NGO பொருந்துதல்',
    foodSafety: 'உணவு பாதுகாப்பு டைமர்',
    photoVerification: 'ফটো சत்যাপन (AI)',
    demandAware: 'கோரிக்கை-விழிப்பு விநியோகம்',
    falsePrevention: 'பொய்யான தடயம் தடுப்பு',
    heatmap: 'உயிந்த உணவு மீட்டெடுப்பு வரைபட',
    impactMeter: 'கார்பன் & தட்ப வெப்பநிலை தாக்கம்',
    emergencyMode: 'அவசர பசி முறை',
    accessibility: 'அமைப்புகள் & அ accessibility',
    
    // Buttons
    enable: 'இயக்கவும்',
    disable: 'முடக்கவும்',
    save: 'மாற்றங்களை சேமிக்கவும்',
    cancel: 'ரத்து செய்யவும்',
    
    // Messages
    welcomeBack: 'திரும்பி வந்ததற்கு நன்றி!',
    goodMorning: 'காலை வணக்கம்',
    letsSaveFood: 'சுவையான உணவைக் காப்போம்...',
    urgentNeed: 'அவசரம்: 50+ பேருக்கு இப்போது உணவு தேவை',
    locationAway: 'தொலைவில்',
    respondNow: 'இப்போது பதிலளிக்கவும்',

    backToDashboard: 'டாஷ்போர்டுக்குத் திரும்பு',
    postSurplusFood: 'உணவு பதிவு',
    freshCheck: 'புதிய சோதனை',
    details: 'விவரங்கள்',
    review: 'மதிப்பீடு',
    success: 'வெற்றி',
    reviewYourPost: 'உங்கள் பதிவை மதிப்பீடு',
    foodName: 'உணவு பெயர்',
    quantityServings: 'அளவு (பரிமாற்றங்கள்)',
    safetyWindow: 'பாதுகாப்பு நேரம்',
    temperatureRange: 'வெப்பநிலை வரம்பு',
    availableFor: 'கிடைக்கும் நேரம்',
    qualityScore: 'தர மதிப்பு',
    notSpecified: 'குறிப்பிடப்படவில்லை',
    confirmAndPost: 'உறுதி & பதிவு',
    posting: 'பதிவு செய்கிறது…',
    failedToPostFood: 'உணவு பதிவு தோல்வி. மீண்டும் முயற்சிக்கவும்.',
    numberOfServings: 'பரிமாற்றங்களின் எண்ணிக்கை',
    minTemp: 'குறைந்த வெப்பம்',
    maxTemp: 'அதிக வெப்பம்',
    enterPickupAddress: 'முழு அடையாள முகவரியை உள்ளிடவும்',
    specialInstructions: 'உணவு பற்றிய சிறப்பு வழிமுறைகள் அல்லது விவரங்கள்',
    signIn: 'உள்நுழை',
    signUp: 'பதிவு செய்',
    createAccount: 'கணக்கு உருவாக்கு',
    createAccountSubtitle: 'தொடங்க உங்கள் கணக்கை உருவாக்குங்கள்',
    creatingAccount: 'கணக்கு உருவாக்கப்படுகிறது…',
    dontHaveAccount: 'கணக்கு இல்லையா?',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    backToSignIn: 'உள்நுழைக்கு திரும்பு',
    fullNameRequired: 'முழு பெயர் தேவை',
    fullNameMinLength: 'பெயர் குறைந்தது 2 எழுத்துகள்',
    emailRequired: 'மின்னஞ்சல் தேவை',
    invalidEmail: 'செல்லுபடியான மின்னஞ்சலை உள்ளிடவும்',
    passwordRequired: 'கடவுச்சொல் தேவை',
    passwordMinLength: 'கடவுச்சொல் குறைந்தது 8 எழுத்துகள்',
    confirmPassword: 'கடவுச்சொல்லை உறுதிசெய்',
    passwordsDoNotMatch: 'கடவுச்சொற்கள் பொருந்தவில்லை',
    registrationFailed: 'பதிவு தோல்வி. மீண்டும் முயற்சிக்கவும்.',
    enterYourName: 'உங்கள் முழு பெயர்',
    personalDetails: 'தனிப்பட்ட விவரங்கள்',
    personalDetailsSubtitle: 'அமைப்புகள் உங்களைத் தொடர்பு கொள்ள தொலைபேசி/முகவரியைச் சேர்க்கவும் (விரும்பினால்).',
    optional: 'விரும்பினால்',
    enterPhone: 'எ.கா. +91 98765 43210',
    enterAddress: 'நகரம், பகுதி அல்லது முழு முகவரி',
    skip: 'தவிர்',
    saveAndContinue: 'சேமி மற்றும் தொடர்',
    saving: 'சேமிக்கிறது…',
    saveFailed: 'சேமிக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    emailPlaceholder: 'மின்னஞ்சல்',
    passwordPlaceholder: 'கடவுச்சொல்',
    rememberMe: 'என்னை நினைவில் கொள்',
    browseWithoutSignIn: 'உள்நுழையாமல் உலாவு',
    backToFreshCheck: 'புதிய சோதனைக்கு திரும்பு',
    continueToReview: 'மதிப்பீட்டிற்கு தொடர்',
    safetyWindowMinutes: 'பாதுகாப்பு நேரம் (நிமிடங்கள்)',
    storageTempRange: 'சேமிப்பு வெப்பநிலை வரம்பு (°C)',
    availableForHours: 'கிடைக்கும் நேரம் (மணி)',
    locationName: 'இடத்தின் பெயர்',
    fullAddress: 'முழு முகவரி',
    additionalNotes: 'கூடுதல் குறிப்புகள்',
    editDetails: 'விவரங்களை திருத்து',
    goToDashboard: 'டாஷ்போர்டுக்கு செல்',
    postAnother: 'மற்றொன்று பதிவு',
    foodPostedSuccess: 'உணவு வெற்றிகரமாக பதிவு செய்யப்பட்டது!',
    foodPostedSuccessDesc: 'உங்கள் மிகுதி உணவு பதிவு செய்யப்பட்டு NGO-கள் கோரிக்கை செய்ய கிடைக்கிறது. பொருந்திய NGO-களுக்கு விரைவில் அறிவிக்கப்படும்.',
    min: 'குறைந்த',
    max: 'அதிக',
    back: 'பின்செல்',
    signInWithEmailPassword: 'உங்கள் மின்னஞ்சல் மற்றும் கடவுச்சொல்லுடன் உள்நுழையுங்கள்',
    enterYourEmail: 'மின்னஞ்சலை உள்ளிடவும்',
    enterYourPassword: 'கடவுச்சொல்லை உள்ளிடவும்',
    signingIn: 'உள்நுழைகிறது…',
    browseSiteWithoutSignIn: 'உள்நுழையாமல் தளத்தை உலாவுங்கள்',
    staySignedIn: 'இந்த சாதனத்தில் உள்நுழைந்தே இருங்கள்.',
    signOutWhenClose: 'உலாவியை மூடும்போது வெளியேறு.',

    welcome: 'திரும்பி வந்ததற்கு நன்றி!',
    welcomeBackWithName: 'திரும்பி வந்ததற்கு நன்றி, {{name}}!',
    missionToday: 'உங்கள் உணவு மீட்புப் பணி இன்று எவ்வாறு உள்ளது',
    storageTemperature: 'சேமிப்பு வெப்பநிலை',
    hours: 'மணி',
    equivalent: 'சமமான',
    matchedStatus: 'பொருத்தப்பட்டது',
    acceptedStatus: 'ஏற்றுக்கொள்ளப்பட்டது',
    deliveredStatus: 'வழங்கப்பட்டது',
    pickedUpStatus: 'எடுக்கப்பட்டது',
    makingADifference: 'நீங்கள் வித்தியாசம் செய்கிறீர்கள். தாக்கத்தைத் தொடர்ந்து வழங்குங்கள்!',
    postSurplus: 'உணவு பதிவு',
    myMatches: 'என் பொருத்தங்கள்',
    impact: 'தாக்கம்',
    weeklyTrend: 'வாரவாரி தாக்கம் போக்கு',
    foodSafetyTimer: 'உணவு பாதுகாப்பு டைமர்',
    liveDeliveryTrack: 'நேரடி டெலிவரி தடசம்',
    carbonSaved: 'கார்பன் சேமிக்கப்பட்டது',
    verification: 'சரிபார்ப்பு',
    features: 'அம்சங்கள்',
    donor: 'நன்கொடையாளர்',
    freshnessChecker: 'புதுமை உணவு சோதனை',
    donating: 'நன்கொடை',
    ngo: 'NGO',
    report: 'அறிக்கை',
    aboutUs: 'எங்களைப் பற்றி',
    quickActions: 'விரைவு செயல்கள்',
    recentActivity: 'இன்றைய செயல்பாடு',
    pendingMatches: 'நிலுவை பொருத்தங்கள்',
    activeDeliveries: 'செயலில் உள்ள டெலிவரிகள்',
    didYouKnow: 'உங்களுக்கு தெரியுமா?',
    tipText: 'ஒவ்வொரு 1 கிலோ உணவு மீட்பும் ~2.5 கிலோ CO₂ சேமிக்கிறது.',
    neededFoodMap: 'தேவையான உணவு பகுதிகள்',
    howYouCanHelp: 'நீங்கள் எவ்வாறு உதவ முடியும்',
    postFoodNow: 'இப்போது உணவு பதிவு',
    viewMatches: 'பொருத்தங்களைக் காண்க',
    seeImpact: 'தாக்கத்தைக் காண்க',
    adminOrg: 'நிர்வாகம் / அமைப்பு',
    profile: 'சுயவிவரம்',
    goToSettings: 'அமைப்புகளுக்குச் செல்ல',
    postsMatchedToday: 'இன்று NGO-களுடன் பொருந்திய பதிவுகள்',
    deliveryCompleted: 'டெலிவரி முடிந்தது',
    matchAwaiting: 'உங்கள் பதிலுக்காக காத்திருக்கும் பொருத்தம்',
    getStartedNow: 'இப்போது தொடங்குங்கள்',
    thisWeek: 'இந்த வாரம்',
    thisYear: 'இந்த ஆண்டு',
    keyInsights: 'முக்கிய நுண்ணறிவுகள்',
    periodComparison: 'காலகட்ட ஒப்பீடு',
    lastWeek: 'கடந்த வாரம்',
    lastMonth: 'கடந்த மாதம்',
    lastYear: 'கடந்த ஆண்டு',
    change: 'மாற்றம்',
    ofTotal: 'மொத்தத்தில்',
    yourMatches: 'உங்கள் பொருத்தங்கள்',
    seeWhichNGOs: 'உங்கள் உணவில் எந்த NGO-கள் ஆர்வமாக உள்ளன என்பதைப் பார்க்கவும்',
    organization: 'அமைப்பு',
    donationValue: 'நன்கொடை மதிப்பு',
    accept: 'ஏற்க',
    decline: 'நிராகரி',
    startTravel: 'பயணத்தைத் தொடங்குங்கள்',
    viewOnMap: 'வரைபடத்தில் தூரத்தைக் காணுங்கள்',
    allMatches: 'அனைத்தும்',
    matchPending: 'நிலுவையில்',
    matchAccepted: 'ஏற்றுக்கொள்ளப்பட்டது',
    matchInDelivery: 'டெலிவரியில்',
    matchCompleted: 'முடிந்தது',
    yourImpact: 'உங்கள் தாக்கம்',
    seeHowMuch: 'நீங்கள் எவ்வளவு வித்தியாசத்தை ஏற்படுத்துகிறீர்கள் என்பதைப் பார்க்கவும்',
    aboutResQMeal: 'ResQ Meal பற்றி',
    turningSurplus: 'மிகுதியை உணவாக மாற்றுதல்.',
    fullStackPlatform: 'ResQ Meal என்பது நன்கொடையாளர்கள், NGO-கள் மற்றும் தன்னார்வலர்களை இணைக்கும் ஒரு முழு-ஸ்டேக் தளமாகும்—மிகுதி உணவை மறுபகிர்வு செய்து கழிவுகளைக் குறைத்து பசியை எதிர்கொள்கிறது. உணவை இடுகையிடுங்கள், பொருந்தவும், டெலிவரியைக் கண்காணிக்கவும், உங்கள் தாக்கத்தைப் பார்க்கவும்.',
    ourMission: 'எங்கள் பணி',
    missionText: 'நல்ல உணவு மக்களை அடையும், குப்பைக் கிடங்குகளை அல்ல. நாங்கள் உணவகங்கள் மற்றும் நன்கொடையாளர்களுக்கு மிகுதியை இடுகையிட உதவுகிறோம், அதை தேவையுள்ள NGO-களுடன் பொருத்துகிறோம், மற்றும் ஒவ்வொரு உணவும் கணக்கிடப்படும் வகையில் டெலிவரியைக் கண்காணிக்கிறோம்.',
    ourVision: 'எங்கள் பார்வை',
    visionText: 'மிகுதி உணவு வழக்கமாக மீட்கப்பட்டு, பகிர்ந்து, அளவிடப்படும் ஒரு உலகம்—ஒவ்வொரு சமூகத்திலும் பசி மற்றும் சுற்றுச்சூழல் தாக்கத்தைக் குறைத்தல்.',
    howItWorks: 'இது எவ்வாறு செயல்படுகிறது',
    postSurplusDesc: 'நன்கொடையாளர்கள் அளவு, காலாவதி மற்றும் விருப்பமான AI புதுமையான சோதனையுடன் மிகுதி உணவைச் சேர்க்கிறார்கள்.',
    getMatched: 'பொருந்தவும்',
    getMatchedDesc: 'NGO-கள் தொடர்புடைய பட்டியல்களைப் பார்க்கின்றன; எங்கள் அமைப்பு தேவை மற்றும் தூரத்தின் அடிப்படையில் சிறந்த பொருத்தங்களை பரிந்துரைக்கிறது.',
    confirmDeliver: 'உறுதிப்படுத்தி வழங்குங்கள்',
    confirmDeliverDesc: 'தன்னார்வலர்கள் எடுத்துச் சென்று வழங்குகிறார்கள். நிலையைக் கண்காணித்து டெலிவரி சான்றுடன் முடிக்கவும்.',
    seeImpactDesc: 'சேமிக்கப்பட்ட உணவு, தடுக்கப்பட்ட CO₂ மற்றும் சேமிக்கப்பட்ட நீர் உங்கள் டாஷ்போர்டில் கண்காணிக்கப்பட்டு காட்டப்படுகிறது.',
    websiteFeatures: 'வலைத்தள அம்சங்கள் & விவரங்கள்',
    websiteFeaturesDesc: 'ResQ Meal நன்கொடையாளர்கள், NGO-கள் மற்றும் தன்னார்வலர்களை ஆதரிக்க பின்வரும் அம்சங்களை உள்ளடக்கியது:',
    technologyAI: 'தொழில்நுட்பம் & AI',
    technologyAIText: 'புதிய உணவு சோதனையாளர் தரம் மற்றும் புதுமைக்கான விருப்பமான ML மாதிரிகளைப் பயன்படுத்துகிறது: பட-அடிப்படையிலான (எ.கா. Bedrock/Claude Vision, TFLite, Roboflow YOLO, FreshVision, Food-101 வகைப்பாடு) மற்றும் சுற்றுச்சூழல்-அடிப்படையிலான (வெப்பநிலை, ஈரப்பதம், சேமிப்பு நேரம்). Food-Image-Recognition உணவுகளை வகைப்படுத்தி ஊட்டச்சத்தைத் திரும்பலாம். இவை அனைத்தும் நன்கொடையாளர்கள் மற்றும் NGO-கள் மிகுதி உணவு மறுபகிர்வுக்கு பாதுகாப்பானது என்பதை நம்ப உதவுகிறது.',
    getInvolved: 'ஈடுபடுங்கள்',
    getInvolvedText: 'நன்கொடையாளராக மிகுதியை இடுகையிடுங்கள், NGO-ஆக பொருத்தங்களைக் கோரவும், அல்லது டெலிவரி செய்ய தன்னார்வலராக பதிவு செய்யவும். தொடங்க டாஷ்போர்டு, நன்கொடையாளர், NGO மற்றும் அறிக்கை பிரிவுகளைப் பயன்படுத்தவும். ஆதரவு அல்லது கூட்டாண்மைகளுக்கு, உங்கள் கணக்கு அல்லது அமைப்புகள் மூலம் தொடர்பு கொள்ளவும்.',
    followUs: 'எங்களைப் பின்தொடரவும்',
    eliteMode: 'எலைட் மோட்',
    eliteTitle: 'எலைட் மோட் — மூத்தோருக்கு மரியாதை',
    eliteSubtitle: 'பிள்ளைகளால் பராமரிப்பு இல்லங்களில் விடப்பட்ட மூத்தோருக்கு',
    eliteWho: 'எலைட் மோட் யாருக்கு?',
    eliteWhoDesc: 'பிள்ளைகளால் அனாதை இல்லங்கள் அல்லது பராமரிப்பு இல்லங்களில் விடப்பட்ட மூத்தோர். இந்த பெற்றோர்கள் வழக்கமான நன்கொடை மிகுதி உணவை விரும்புவதில்லை; திருமணம்/விழா உணவிலிருந்தும் பிள்ளைகள் வாங்கிக் கொடுக்கும் உணவிலிருந்தும் சாப்பிடுகிறார்கள்.',
    eliteWhat: 'அவர்கள் என்ன உணவு சாப்பிடுகிறார்கள்?',
    eliteWhatDesc: 'திருமணம் மற்றும் விழா உணவு (திருமணங்கள் மற்றும் நிகழ்வுகளிலிருந்து), திருவிழா உணவு மற்றும் பிள்ளைகள் வாங்கிக் கொடுக்கும் உணவு—வழக்கமான நன்கொடை மிகுதி அல்ல. எலைட் மோட் பராமரிப்பு இல்லங்களையும் மூத்தோரையும் இந்த விருப்ப மூலங்களுடன் இணைக்கிறது.',
    eliteHow: 'எலைட் மோட் எவ்வாறு செயல்படுகிறது',
    eliteHow1: 'பராமரிப்பு இல்லங்கள் அல்லது மூத்தோர் எலைட் மோடிற்கு பதிவு செய்கிறார்கள்.',
    eliteHow2: 'நிகழ்வு கேட்டரர்கள் மற்றும் குடும்பங்கள் திருமணம்/விழா உணவை பட்டியலிடலாம் அல்லது பராமரிப்பில் உள்ள பெற்றோருக்கு ஆர்டர் செய்யலாம்.',
    eliteHow3: 'பதிவு செய்யப்பட்ட பராமரிப்பு இல்லங்களுக்கு உணவு வழங்கப்படுகிறது; மூத்தோர் விரும்பும் உணவைப் பெறுகிறார்கள்.',
    getInvolvedElite: 'உங்கள் பராமரிப்பு இல்லத்தை பதிவு செய்யுங்கள், நிகழ்வு உணவை பட்டியலிடுங்கள், அல்லது பராமரிப்பில் உள்ள பெற்றோருக்கு உணவு ஆர்டர் செய்யுங்கள்.',
    eliteFestivalTitle: 'திருவிழா உணவு',
    eliteFestivalDesc: 'திருவிழா உணவும் ResQ Meal மூலம் வழங்கப்படுகிறது. குடும்பங்களும் கேட்டரர்களும் திருவிழாக்கள் மற்றும் விழாக்களிலிருந்து மிகுதியை பட்டியலிடலாம்; பராமரிப்பு இல்லங்கள் பெறுவதால் மூத்தோர் வளர்ந்த அதே சிறப்பு உணவுகளை அனுபவிக்கிறார்கள்.',
    eliteFestivalServed: 'இந்த இணையதளத்தில் வழங்கப்படுகிறது',
    eliteFestivalEx1: 'தீபாவளி மிட்டாய் & காரம்',
    eliteFestivalEx2: 'பொங்கல் / அறுவடை விழா சிறப்புகள்',
    eliteFestivalEx3: 'ஈத் பிரியானி & மிட்டாய்',
    eliteFestivalEx4: 'கிறிஸ்துமஸ் கேக்குகள் & பலகாரங்கள்',
    eliteFestivalEx5: 'பிற விழா & கொண்டாட்ட உணவுகள்',
    eliteFestivalExamplesLabel: 'இந்த இணையதளத்தில் வழங்கப்படும் உதாரணங்கள்:',
    eliteRegister: 'பதிவு',
    eliteRegisterHome: 'உங்கள் வீட்டை பதிவு செய்யுங்கள்',
    eliteRegisterHomeDesc: 'உங்கள் வீடு அல்லது பராமரிப்பு இல்ல முகவரியைச் சேர்த்து, உங்களிடம் உள்ள உணவுகளை பட்டியலிடுங்கள். தூரம் பார்க்க வரைபடத்தைத் திறக்க "வரைபடத்தில் காண்க" என்பதைக் கிளிக் செய்யுங்கள்.',
    eliteHomeAddress: 'வீட்டு முகவரி',
    eliteHomeAddressPlaceholder: 'தெரு, நகரம், மாநிலம், பின்',
    eliteFoodsAvailable: 'கிடைக்கும் உணவுகள்',
    eliteAddFood: 'உணவு சேர்',
    eliteFoodName: 'உணவு பெயர்',
    eliteFoodType: 'வகை (எ.கா. விழா, கொண்டாட்டம்)',
    eliteQuantity: 'அளவு',
    eliteSubmitRegistration: 'பதிவு சமர்ப்பி',
    eliteViewOnMap: 'வரைபடத்தில் காண்க / வழிகாட்டு',
    eliteMyRegistrations: 'என் பதிவுகள்',
    eliteBackToElite: 'எலைட் மோடிற்கு திரும்பு',
    eliteNoRegistrationsYet: 'இன்னும் பதிவுகள் இல்லை. தொடங்க உங்கள் வீட்டை பதிவு செய்து உணவுகளை பட்டியலிடுங்கள்.',
    eliteEstablishmentType: 'நிறுவன வகை',
    eliteEstablishmentTypePlaceholder: 'எ.கா. பராமரிப்பு இல்லம், மூத்தோர் இல்லம்',
    eliteContactName: 'தொடர்பு நபர் பெயர்',
    eliteContactNamePlaceholder: 'முழு பெயர்',
    eliteContactPhone: 'தொடர்பு தொலைபேசி',
    eliteContactPhonePlaceholder: 'தொலைபேசி எண்',
    eliteResidentCount: 'குடியிருப்பாளர்கள் எண்ணிக்கை (விரும்பினால்)',
    eliteResidentCountPlaceholder: 'எ.கா. 10',
    elitePreferredFoodTypes: 'விரும்பிய உணவு வகைகள் (திருமணம் மற்றும் சிறப்பு நிகழ்வுகள்)',
    elitePreferredWedding: 'திருமண உணவு',
    elitePreferredFestival: 'திருவிழா உணவு',
    elitePreferredCelebration: 'விழா / நிகழ்வு உணவு',
    eliteDietaryNotes: 'உணவு குறிப்புகள் (விரும்பினால்)',
    eliteDietaryNotesPlaceholder: 'எ.கா. சைவ மட்டும்',
    eliteBrowseTitle: 'கிடைக்கும் சிறப்பு நிகழ்வு உணவு',
    eliteBrowseDesc: 'திருமணங்கள், திருவிழாக்கள் மற்றும் விழாக்களிலிருந்து உணவுகள்.',
    eliteDistanceAway: '{{km}} கிமீ தூரம்',
    eliteGetDirections: 'வழிகாட்டு',
    eliteNoEliteFoodsYet: 'இன்னும் சிறப்பு நிகழ்வு உணவு பட்டியலிடப்படவில்லை.',

    clickForDetails: 'விவரங்களுக்கு கிளிக் செய்யவும்',
    backToReport: 'அறிக்கைக்கு திரும்பு',
    detailedReport: 'விரிவான அறிக்கை',
    dailyBreakdown: 'தினசரி பிரிவு',
    weeklyBreakdown: 'வாராந்திர பிரிவு',
    monthlyBreakdown: 'மாதாந்திர பிரிவு',
    topSources: 'முதன்மை மூலங்கள்',
    trendAnalysis: 'இந்த விளக்கப்படம் ஒவ்வொரு நாளுக்கும் விரிவான தரவு புள்ளிகளுடன் வாராந்திர போக்கைக் காட்டுகிறது.',
    lastWeekSummary: 'கடந்த வாரம் நிலையான வளர்ச்சியுடன் சீரான செயல்திறனைக் காட்டியது.',
    lastMonthSummary: 'கடந்த மாதம் வாரத்திற்கு வாரம் அதிகரிக்கும் தாக்கத்துடன் வலுவான வளர்ச்சியை நிரூபித்தது.',
    lastYearSummary: 'கடந்த ஆண்டு மாதாந்திர வளர்ச்சியுடன் முற்போக்கான முன்னேற்றத்தைக் காட்டியது.',

    adminOrgReport: 'அமைப்பு அறிக்கை',
    freshFoodAnalyser: 'புதிய உணவு பகுப்பாய்வு',
    postFood: 'உணவு இடுகை',
    overallReport: 'மொத்த அறிக்கை',
    overallReportDesc: 'உங்கள் அமைப்பின் தாக்கம் மற்றும் செயல்பாட்டின் சுருக்கம். விரிவான விவரங்களுக்கு ஒரு அட்டையைக் கிளிக் செய்யவும்.',
    peopleServed: 'சேவை செய்யப்பட்ட மக்கள்',
    mealsDelivered: 'வழங்கப்பட்ட உணவு',
    deliveriesCompleted: 'முடிக்கப்பட்ட டெலிவரிகள்',
    activeVolunteers: 'செயலில் உள்ள தன்னார்வலர்கள்',
    totalBeneficiaries: 'மொத்த பயனாளிகள்',
    successfulRuns: 'வெற்றிகரமான ரன்கள்',
    deliveries: 'டெலிவரிகள்',
    volunteers: 'தன்னார்வலர்கள்',
    extendedBreakdown: 'விரிவான பிரிவு',
    quarterToDate: 'காலாண்டு முதல்',
    yearToDate: 'ஆண்டு முதல்',
    topLocation: 'முதன்மை இடம்',
    averagePerDelivery: 'ஒரு டெலிவரிக்கு சராசரி',
    totalAllTime: 'மொத்தம் (அனைத்து நேரம்)',
    peakDayThisMonth: 'இந்த மாதத்தின் உச்ச நாள்',
    onTimeRate: 'நேரத்திற்கு விகிதம்',
    totalSuccessful: 'மொத்த வெற்றிகரமான',
    avgDistancePerRun: 'ஒரு ரனுக்கு சராசரி தூரம்',
    newThisMonth: 'இந்த மாதத்தில் புதியது',
    completed5PlusDeliveries: '5+ டெலிவரிகள் முடிக்கப்பட்டது',
    topVolunteerDeliveries: 'முதன்மை தன்னார்வலர் (டெலிவரிகள்)',
    totalActive: 'மொத்த செயலில்',
    retentionRate: 'தக்கவைப்பு விகிதம்',
    equivalentEmissionsAvoided: 'சமமான உமிழ்வுகள் தவிர்க்கப்பட்டது',
    equivalentCarKm: 'சமமான கார் கிமீ',
    equivalentTrees1Year: 'சமமான மரங்கள் (1 ஆண்டு)',
    foodRescued: 'மீட்கப்பட்ட உணவு',
    weightDivertedFromWaste: 'கழிவிலிருந்து திசை திருப்பப்பட்ட எடை',
    primaryCategory: 'முதன்மை வகை',
    partnersInvolved: 'ஈடுபட்ட கூட்டாளர்கள்',
    addFoodDonorsOnly: 'உணவு சேர் (நன்கொடையாளர்கள் மட்டும்)',
    addFoodDonorsDesc: 'நன்கொடையாளராக, எடுப்பு அல்லது டெலிவரி தேவையான உணவைச் சேர்க்கவும். விருப்பமாக எங்கள் AI சோதனையாளருடன் முதலில் புதுமையைச் சரிபார்க்கவும்; பின்னர் படிவத்தை நிரப்பவும். இது தன்னார்வலர் பக்கத்தில் தோன்றும்.',
    skipFillForm: 'தவிர்க்க → படிவத்தை நிரப்பு',
    checkFreshnessFirstOptional: 'முதலில் புதுமையைச் சரிபார்க்கவும் (விருப்பமானது)',
    foodNamePlaceholder: 'எ.கா. சாதம் மற்றும் கறி, ரொட்டி ரோல்கள்',
    type: 'வகை',
    foodType: 'உணவு வகை',
    servings: 'பரிமாற்றங்கள்',
    servingsPlaceholder: 'எ.கா. 10',
    addressPickupLocation: 'முகவரி / எடுப்பு இடம்',
    addressPlaceholder: 'எ.கா. 123 மெயின் ஸ்ட்ரீட், சென்னை',
    descriptionOptional: 'விளக்கம் (விருப்பமானது)',
    descriptionPlaceholder: 'தன்னார்வலர்களுக்கான குறிப்புகள்',
    adding: 'சேர்க்கிறது…',
    addFood: 'உணவு சேர்',
    foodYouAddedVisibleToVolunteers: 'நீங்கள் சேர்த்த உணவு (தன்னார்வலர்களுக்கு தெரியும்)',
    noFoodAddedYet: 'இன்னும் உணவு சேர்க்கப்படவில்லை.',
    foodNameAndAddressRequired: 'உணவு பெயர் மற்றும் முகவரி தேவை.',
    foodAddedSuccess: 'உணவு சேர்க்கப்பட்டது. இது தன்னார்வலர் பக்கத்தில் தோன்றும்.',
    failedToAddFood: 'உணவு சேர்க்க முடியவில்லை.',
    monthlyComparison: 'மாதாந்திர ஒப்பீடு',
    thisMonthMeals: 'இந்த மாதம் (உணவு)',
    lastMonthMeals: 'கடந்த மாதம் (உணவு)',
    vsLastMonth: 'கடந்த மாதத்துடன் ஒப்பிடும்போது',
    impactTrends: 'தாக்கம் போக்குகள்',
    impactTrendsDesc: 'கடந்த 6 மாதங்களில் மாதாந்திர உணவு வழங்கப்பட்டது மற்றும் மக்கள் சேவை செய்யப்பட்டது.',
    overviewAllTime: 'கண்ணோட்டம் (அனைத்து நேரம்)',
    keyMetricsComparison: 'முக்கிய அளவீடுகள் ஒப்பீடு',
    foodType_meals: 'உணவு',
    foodType_vegetables: 'காய்கறிகள்',
    foodType_baked: 'சுட்ட',
    foodType_dairy: 'பால் பொருட்கள்',
    foodType_fruits: 'பழங்கள்',
    foodType_others: 'மற்றவை',
    loading: 'ஏற்றுகிறது…',
    clearFreshnessResult: 'புதுமை முடிவை அழிக்க',
    value: 'மதிப்பு',
    
    // Volunteer Mode
    volunteerMode: 'தன்னார்வலர் முறை',
    volunteerModeDescription: 'அமைப்புகளிடமிருந்து கிடைக்கும் உணவு மற்றும் உங்களுக்கு ஒதுக்கப்பட்ட டெலிவரிகளை இங்கே பார்க்கவும்.',
    availableFoodFromDonors: 'நன்கொடையாளர்களிடமிருந்து கிடைக்கும் உணவு',
    availableFoodFromDonorsDesc: 'நன்கொடையாளர்களால் சேர்க்கப்பட்ட உணவு. தன்னார்வலர்கள் பார்த்து புதுமையை மட்டுமே சரிபார்க்க முடியும்.',
    noFoodFromDonors: 'இப்போது நன்கொடையாளர்களிடமிருந்து உணவு இல்லை.',
    noFoodFromDonorsDesc: 'நன்கொடையாளர்கள் உணவைச் சேர்க்கும்போது, அது இங்கே தோன்றும். ஒவ்வொரு உருப்படிக்கும் புதுமையை நீங்கள் சரிபார்க்கலாம்.',
    myDeliveries: 'என் டெலிவரிகள்',
    noDeliveriesAssigned: 'இன்னும் டெலிவரிகள் ஒதுக்கப்படவில்லை.',
    noDeliveriesAssignedDesc: 'உங்கள் அமைப்பு உங்களுக்கு டெலிவரிகளை ஒதுக்கும்.',
    status: 'நிலை',
  },
  hi: {
    // Navigation & Menu
    dashboard: 'डैशबोर्ड',
    myPosts: 'मेरी पोस्ट्स',
    matches: 'मैच्स',
    notifications: 'सूचनाएं',
    settings: 'सेटिंग्स',
    logout: 'लॉग आउट',
    
    // Dashboard
    todayImpact: 'आज का प्रभाव',
    weeklyImpact: 'साप्ताहिक प्रभाव ट्रेंड',
    mealsDistributed: 'वितरित भोजन',
    co2Prevented: 'रोका गया CO₂ (किग्रा)',
    waterSaved: 'बचाया गया पानी (एल)',
    emergencyAlerts: 'आपातकालीन सतर्कताएं',
    thisMonth: 'इस महीने',
    mealsSaved: 'भोजन बचाया गया',
    foodDiverted: 'भोजन हटाया गया',
    co2Prevented2: 'CO₂ रोका गया',
    
    // Food Cards
    quantity: 'मात्रा',
    expiry: 'एक्सपायरी',
    distance: 'दूरी',
    freshness: 'ताजापन',
    requestFood: 'इस भोजन का अनुरोध करें',
    availableFood: 'आज का उपलब्ध भोजन',
    recommendedForYou: 'आपके लिए अनुशंसित',
    seeAll: 'सभी देखें',
    
    // Search & Filter
    search: 'खोज',
    searchFood: 'अतिरिक्त भोजन खोजें...',
    groceries: 'किराना सामान',
    meals: 'भोजन',
    bakedGoods: 'बेक किए हुए सामान',
    listView: 'सूची दृश्य',
    mapView: 'मानचित्र दृश्य',
    
    // Settings
    userDetails: 'उपयोगकर्ता विवरण',
    darkMode: 'डार्क मोड',
    language: 'भाषा',
    chooseLanguage: 'आप कौन सी भाषा इस्तेमाल करना चाहेंगे?',
    chooseLanguageSubtitle: 'वेबसाइट के लिए अपनी पसंदीदा भाषा चुनें।',
    changeLanguage: 'भाषा बदलें',
    english: 'अंग्रेजी',
    tamil: 'तमिल',
    hindi: 'हिंदी',
    email: 'ईमेल',
    password: 'पासवर्ड',
    phone: 'फोन',
    location: 'स्थान',
    role: 'भूमिका',
    name: 'नाम',
    address: 'पता',
    preferences: 'वरीयताएँ',
    restaurant: 'रेस्तरां',
    volunteer: 'स्वयंसेवक',
    organizationInfo: 'संगठन जानकारी',
    orgName: 'संगठन का नाम',
    orgType: 'संगठन का प्रकार',
    license: 'लाइसेंस/पंजीकरण संख्या',
    website: 'वेबसाइट',
    registrationDate: 'पंजीकरण तिथि',
    donationStats: 'दान आंकड़े',
    totalDonations: 'कुल दान',
    mealsContributed: 'योगदान दिए गए भोजन',
    moneyValue: 'अनुमानित मूल्य',
    impactContribution: 'आपका प्रभाव योगदान',
    saved: 'सेटिंग्स सफलतापूर्वक सहेजी गईं!',
    
    // Features (for hamburger menu)
    oneClickPosting: 'वन-क्लिक सरप्लस पोस्टिंग',
    smartMatching: 'स्मार्ट NGO मिलान',
    foodSafety: 'खाद्य सुरक्षा टाइमर',
    photoVerification: 'फोटो सत्यापन (AI)',
    demandAware: 'मांग-जागरूक पुनर्वितरण',
    falsePrevention: 'गलत अधिशेष रोकथाम',
    heatmap: 'लाइव खाद्य बचाव हीटमैप',
    impactMeter: 'कार्बन और जलवायु प्रभाव',
    emergencyMode: 'आपातकालीन भूख मोड',
    accessibility: 'सेटिंग्स और पहुंच',
    
    // Buttons
    enable: 'सक्षम करें',
    disable: 'अक्षम करें',
    save: 'परिवर्तन सहेजें',
    cancel: 'रद्द करें',
    
    // Messages
    welcomeBack: 'वापसी पर स्वागत है!',
    goodMorning: 'शुभ प्रभात',
    letsSaveFood: 'चलिए कुछ स्वादिष्ट खाना बचाते हैं...',
    urgentNeed: 'अत्यावश्यक: 50+ लोगों को अभी भोजन की जरूरत है',
    locationAway: 'दूर',
    respondNow: 'अभी जवाब दें',

    backToDashboard: 'डैशबोर्ड पर वापस जाएं',
    postSurplusFood: 'अतिरिक्त भोजन पोस्ट करें',
    freshCheck: 'ताजगी जांच',
    details: 'विवरण',
    review: 'समीक्षा',
    success: 'सफलता',
    reviewYourPost: 'अपनी पोस्ट की समीक्षा करें',
    foodName: 'भोजन का नाम',
    quantityServings: 'मात्रा (सर्विंग)',
    safetyWindow: 'सुरक्षा समय',
    temperatureRange: 'तापमान सीमा',
    availableFor: 'उपलब्ध समय',
    qualityScore: 'गुणवत्ता स्कोर',
    notSpecified: 'निर्दिष्ट नहीं',
    confirmAndPost: 'पुष्टि करें और पोस्ट करें',
    posting: 'पोस्ट हो रहा है…',
    failedToPostFood: 'भोजन पोस्ट करने में विफल। कृपया पुनः प्रयास करें।',
    numberOfServings: 'सर्विंग की संख्या',
    minTemp: 'न्यून ताप',
    maxTemp: 'अधिकतम ताप',
    enterPickupAddress: 'पूरा पिकअप पता दर्ज करें',
    specialInstructions: 'भोजन के बारे में विशेष निर्देश या विवरण',
    signIn: 'साइन इन करें',
    signUp: 'साइन अप',
    createAccount: 'खाता बनाएं',
    createAccountSubtitle: 'शुरू करने के लिए अपना खाता बनाएं',
    creatingAccount: 'खाता बन रहा है…',
    dontHaveAccount: 'खाता नहीं है?',
    alreadyHaveAccount: 'पहले से खाता है?',
    backToSignIn: 'साइन इन पर वापस',
    fullNameRequired: 'पूरा नाम आवश्यक है',
    fullNameMinLength: 'नाम कम से कम 2 अक्षर',
    emailRequired: 'ईमेल आवश्यक है',
    invalidEmail: 'कृपया वैध ईमेल दर्ज करें',
    passwordRequired: 'पासवर्ड आवश्यक है',
    passwordMinLength: 'पासवर्ड कम से कम 8 अक्षर',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    passwordsDoNotMatch: 'पासवर्ड मेल नहीं खाते',
    registrationFailed: 'पंजीकरण विफल। कृपया पुनः प्रयास करें।',
    enterYourName: 'आपका पूरा नाम',
    personalDetails: 'व्यक्तिगत विवरण',
    personalDetailsSubtitle: 'संगठन आपसे संपर्क कर सकें (वैकल्पिक)।',
    optional: 'वैकल्पिक',
    enterPhone: 'जैसे +91 98765 43210',
    enterAddress: 'शहर, क्षेत्र या पूरा पता',
    skip: 'छोड़ें',
    saveAndContinue: 'सहेजें और जारी रखें',
    saving: 'सहेज रहा है…',
    saveFailed: 'सहेजना विफल। कृपया पुनः प्रयास करें।',
    emailPlaceholder: 'ईमेल',
    passwordPlaceholder: 'पासवर्ड',
    rememberMe: 'मुझे याद रखें',
    browseWithoutSignIn: 'साइन इन किए बिना ब्राउज़ करें',
    backToFreshCheck: 'ताजगी जांच पर वापस जाएं',
    continueToReview: 'समीक्षा के लिए जारी रखें',
    safetyWindowMinutes: 'सुरक्षा समय (मिनट)',
    storageTempRange: 'भंडारण तापमान सीमा (°C)',
    availableForHours: 'उपलब्ध समय (घंटे)',
    locationName: 'स्थान का नाम',
    fullAddress: 'पूरा पता',
    additionalNotes: 'अतिरिक्त नोट',
    editDetails: 'विवरण संपादित करें',
    goToDashboard: 'डैशबोर्ड पर जाएं',
    postAnother: 'दूसरा पोस्ट करें',
    foodPostedSuccess: 'भोजन सफलतापूर्वक पोस्ट हो गया!',
    foodPostedSuccessDesc: 'आपका अधिशेष भोजन पोस्ट हो गया है और अब NGO द्वारा अनुरोध के लिए उपलब्ध है। मिलान वाले NGO को शीघ्र सूचित किया जाएगा।',
    min: 'न्यून',
    max: 'अधिकतम',
    back: 'वापस',
    signInWithEmailPassword: 'अपने ईमेल और पासवर्ड से साइन इन करें',
    enterYourEmail: 'अपना ईमेल दर्ज करें',
    enterYourPassword: 'अपना पासवर्ड दर्ज करें',
    signingIn: 'साइन इन हो रहा है…',
    browseSiteWithoutSignIn: 'बिना साइन इन किए साइट ब्राउज़ करें',
    staySignedIn: 'इस डिवाइस पर साइन इन रहें।',
    signOutWhenClose: 'ब्राउज़र बंद करने पर साइन आउट करें।',

    welcome: 'वापसी पर स्वागत है!',
    welcomeBackWithName: 'वापसी पर स्वागत है, {{name}}!',
    missionToday: 'आज आपके खाद्य बचाव मिशन के साथ क्या हो रहा है',
    storageTemperature: 'भंडारण तापमान',
    hours: 'घंटे',
    equivalent: 'समकक्ष',
    matchedStatus: 'मैच्ड',
    acceptedStatus: 'स्वीकृत',
    deliveredStatus: 'वितरित',
    pickedUpStatus: 'उठाया गया',
    makingADifference: 'आप बदलाव ला रहे हैं। प्रभाव देना जारी रखें!',
    postSurplus: 'अतिरिक्त भोजन पोस्ट करें',
    myMatches: 'मेरे मैच',
    impact: 'प्रभाव',
    weeklyTrend: 'साप्ताहिक प्रभाव प्रवृत्ति',
    foodSafetyTimer: 'खाद्य सुरक्षा टाइमर',
    liveDeliveryTrack: 'लाइव डिलीवरी ट्रैकिंग',
    carbonSaved: 'कार्बन बचाया गया',
    verification: 'सत्यापन',
    features: 'विशेषताएं',
    donor: 'दानदाता',
    freshnessChecker: 'ताजगी भोजन जांच',
    donating: 'दान',
    ngo: 'NGO',
    report: 'रिपोर्ट',
    aboutUs: 'हमारे बारे में',
    quickActions: 'त्वरित कार्य',
    recentActivity: 'आज की गतिविधि',
    pendingMatches: 'लंबित मैच',
    activeDeliveries: 'सक्रिय डिलीवरी',
    didYouKnow: 'क्या आप जानते हैं?',
    tipText: 'हर 1 किलो बचाया भोजन ~2.5 किलो CO₂ बचाता है।',
    neededFoodMap: 'जरूरत वाले खाद्य क्षेत्र',
    howYouCanHelp: 'आप कैसे मदद कर सकते हैं',
    postFoodNow: 'अभी भोजन पोस्ट करें',
    viewMatches: 'मैच देखें',
    seeImpact: 'प्रभाव देखें',
    adminOrg: 'एडमिन / संगठन',
    profile: 'प्रोफ़ाइल',
    goToSettings: 'सेटिंग्स पर जाएं',
    postsMatchedToday: 'आज NGO के साथ मेल खाने वाले पोस्ट',
    deliveryCompleted: 'डिलीवरी पूरी',
    matchAwaiting: 'आपके जवाब का इंतजार कर रहा मैच',
    getStartedNow: 'अभी शुरू करें',
    thisWeek: 'इस सप्ताह',
    thisYear: 'इस वर्ष',
    keyInsights: 'मुख्य अंतर्दृष्टि',
    periodComparison: 'अवधि तुलना',
    lastWeek: 'पिछला सप्ताह',
    lastMonth: 'पिछला महीना',
    lastYear: 'पिछला वर्ष',
    change: 'परिवर्तन',
    ofTotal: 'कुल का',
    yourMatches: 'आपके मैच',
    seeWhichNGOs: 'देखें कि कौन से NGO आपके भोजन में रुचि रखते हैं',
    organization: 'संगठन',
    donationValue: 'दान मूल्य',
    accept: 'स्वीकार करें',
    decline: 'अस्वीकार करें',
    startTravel: 'यात्रा शुरू करें',
    viewOnMap: 'मानचित्र पर दूरी देखें',
    allMatches: 'सभी',
    matchPending: 'लंबित',
    matchAccepted: 'स्वीकृत',
    matchInDelivery: 'डिलीवरी में',
    matchCompleted: 'पूर्ण',
    yourImpact: 'आपका प्रभाव',
    seeHowMuch: 'देखें कि आप कितना अंतर बना रहे हैं',
    aboutResQMeal: 'ResQ Meal के बारे में',
    turningSurplus: 'अधिशेष को भोजन में बदलना।',
    fullStackPlatform: 'ResQ Meal एक पूर्ण-स्टैक प्लेटफॉर्म है जो दानदाताओं, NGO और स्वयंसेवकों को जोड़ता है ताकि अधिशेष भोजन का पुनर्वितरण किया जा सके—कचरे को कम करना और भूख से लड़ना। भोजन पोस्ट करें, मेल खाएं, डिलीवरी ट्रैक करें, और अपना प्रभाव देखें।',
    ourMission: 'हमारा मिशन',
    missionText: 'यह सुनिश्चित करना कि अच्छा भोजन लोगों तक पहुंचे, लैंडफिल नहीं। हम रेस्तरां और दानदाताओं को अधिशेष पोस्ट करने में मदद करते हैं, इसे जरूरतमंद NGO से मिलाते हैं, और डिलीवरी को ट्रैक करते हैं ताकि हर भोजन मायने रखे।',
    ourVision: 'हमारी दृष्टि',
    visionText: 'एक ऐसी दुनिया जहां अधिशेष भोजन नियमित रूप से बचाया, साझा और मापा जाता है—हर समुदाय में भूख और पर्यावरणीय प्रभाव को कम करना।',
    howItWorks: 'यह कैसे काम करता है',
    postSurplusDesc: 'दानदाता मात्रा, समाप्ति और वैकल्पिक AI ताजगी जांच के साथ अधिशेष भोजन जोड़ते हैं।',
    getMatched: 'मेल खाएं',
    getMatchedDesc: 'NGO प्रासंगिक सूचियां देखते हैं; हमारी प्रणाली आवश्यकता और दूरी के आधार पर सर्वोत्तम मैच सुझाती है।',
    confirmDeliver: 'पुष्टि करें और वितरित करें',
    confirmDeliverDesc: 'स्वयंसेवक ले जाते हैं और वितरित करते हैं। स्थिति ट्रैक करें और डिलीवरी प्रमाण के साथ पूरा करें।',
    seeImpactDesc: 'बचाए गए भोजन, रोके गए CO₂ और बचाया गया पानी आपके डैशबोर्ड में ट्रैक और दिखाया जाता है।',
    websiteFeatures: 'वेबसाइट सुविधाएं और विवरण',
    websiteFeaturesDesc: 'ResQ Meal में दानदाताओं, NGO और स्वयंसेवकों का समर्थन करने के लिए निम्नलिखित सुविधाएं शामिल हैं:',
    technologyAI: 'प्रौद्योगिकी और AI',
    technologyAIText: 'फ्रेश फूड चेकर गुणवत्ता और ताजगी के लिए वैकल्पिक ML मॉडल का उपयोग करता है: छवि-आधारित (जैसे Bedrock/Claude Vision, TFLite, Roboflow YOLO, FreshVision, Food-101 वर्गीकरण) और पर्यावरण-आधारित (तापमान, आर्द्रता, भंडारण समय)। Food-Image-Recognition व्यंजनों को वर्गीकृत कर सकता है और पोषण लौटा सकता है। यह सब दानदाताओं और NGO को भरोसा दिलाने में मदद करता है कि अधिशेष भोजन पुनर्वितरण के लिए सुरक्षित है।',
    getInvolved: 'शामिल हों',
    getInvolvedText: 'दानदाता के रूप में अधिशेष पोस्ट करें, NGO के रूप में मैच का अनुरोध करें, या वितरित करने के लिए स्वयंसेवक के रूप में साइन अप करें। शुरू करने के लिए डैशबोर्ड, दानदाता, NGO और रिपोर्ट अनुभागों का उपयोग करें। समर्थन या साझेदारी के लिए, अपने खाते या सेटिंग्स के माध्यम से संपर्क करें।',
    followUs: 'हमें फॉलो करें',
    eliteMode: 'एलीट मोड',
    eliteTitle: 'एलीट मोड — बुजुर्गों के लिए सम्मान',
    eliteSubtitle: 'उन बुजुर्गों के लिए जिन्हें उनके बच्चों ने देखभाल घरों में छोड़ दिया',
    eliteWho: 'एलीट मोड किसके लिए है?',
    eliteWhoDesc: 'बुजुर्ग जिन्हें उनके बच्चों ने अनाथालयों या देखभाल घरों में छोड़ दिया। ये माता-पिता अक्सर नियमित दान किए गए अधिशेष भोजन को पसंद नहीं करते; वे शादी/उत्सव के भोजन और बच्चों द्वारा मंगवाए गए भोजन से खाते हैं।',
    eliteWhat: 'वे क्या भोजन खाते हैं?',
    eliteWhatDesc: 'शादी और उत्सव का भोजन (विवाह और कार्यक्रमों से), त्योहारी भोजन और बच्चों द्वारा मंगवाया गया भोजन—नियमित दान अधिशेष नहीं। एलीट मोड देखभाल घरों और बुजुर्गों को इन पसंदीदा स्रोतों से जोड़ता है।',
    eliteHow: 'एलीट मोड कैसे काम करता है',
    eliteHow1: 'देखभाल घर या बुजुर्ग एलीट मोड के लिए पंजीकरण करते हैं।',
    eliteHow2: 'इवेंट कैटरर और परिवार शादी/उत्सव भोजन सूचीबद्ध कर सकते हैं या देखभाल में माता-पिता के लिए ऑर्डर दे सकते हैं।',
    eliteHow3: 'पंजीकृत देखभाल घरों को भोजन पहुंचाया जाता है ताकि बुजुर्गों को वह भोजन मिले जो वे पसंद करते हैं।',
    getInvolvedElite: 'अपना देखभाल घर पंजीकृत करें, इवेंट भोजन सूचीबद्ध करें, या देखभाल में माता-पिता के लिए भोजन ऑर्डर करें।',
    eliteFestivalTitle: 'त्योहारी भोजन',
    eliteFestivalDesc: 'त्योहारी भोजन भी ResQ Meal के जरिए परोसा जाता है। परिवार और कैटरर त्योहारों और उत्सवों से बचा भोजन सूचीबद्ध कर सकते हैं; देखभाल घरों को मिलता है ताकि बुजुर्गों को वही विशेष भोजन मिले जो उन्होंने बचपन में खाया।',
    eliteFestivalServed: 'इस वेबसाइट पर परोसा जाता है',
    eliteFestivalEx1: 'दिवाली मिठाई और नमकीन',
    eliteFestivalEx2: 'पोंगल / हार्वेस्ट उत्सव विशेष',
    eliteFestivalEx3: 'ईद बिरयानी और मिठाई',
    eliteFestivalEx4: 'क्रिसमस केक और व्यंजन',
    eliteFestivalEx5: 'अन्य त्योहार और उत्सव व्यंजन',
    eliteFestivalExamplesLabel: 'इस वेबसाइट पर परोसे जाने वाले उदाहरण:',
    eliteRegister: 'पंजीकरण',
    eliteRegisterHome: 'अपना घर पंजीकृत करें',
    eliteRegisterHomeDesc: 'अपना घर या देखभाल घर का पता जोड़ें और उपलब्ध भोजन की सूची दें। दूरी देखने के लिए मानचित्र खोलने हेतु "मानचित्र पर देखें" क्लिक करें।',
    eliteHomeAddress: 'घर का पता',
    eliteHomeAddressPlaceholder: 'गली, शहर, राज्य, पिन',
    eliteFoodsAvailable: 'उपलब्ध भोजन',
    eliteAddFood: 'भोजन जोड़ें',
    eliteFoodName: 'भोजन का नाम',
    eliteFoodType: 'प्रकार (जैसे त्योहार, उत्सव)',
    eliteQuantity: 'मात्रा',
    eliteSubmitRegistration: 'पंजीकरण जमा करें',
    eliteViewOnMap: 'मानचित्र पर देखें / दिशा-निर्देश',
    eliteMyRegistrations: 'मेरे पंजीकरण',
    eliteBackToElite: 'एलीट मोड पर वापस',
    eliteNoRegistrationsYet: 'अभी तक कोई पंजीकरण नहीं। शुरू करने के लिए अपना घर पंजीकृत करें और भोजन सूचीबद्ध करें।',
    eliteEstablishmentType: 'संस्थान का प्रकार',
    eliteEstablishmentTypePlaceholder: 'जैसे देखभाल घर, वृद्धाश्रम',
    eliteContactName: 'संपर्क व्यक्ति का नाम',
    eliteContactNamePlaceholder: 'पूरा नाम',
    eliteContactPhone: 'संपर्क फ़ोन',
    eliteContactPhonePlaceholder: 'फ़ोन नंबर',
    eliteResidentCount: 'निवासियों की संख्या (वैकल्पिक)',
    eliteResidentCountPlaceholder: 'जैसे 10',
    elitePreferredFoodTypes: 'पसंदीदा भोजन प्रकार (शादी और विशेष आयोजन)',
    elitePreferredWedding: 'शादी का भोजन',
    elitePreferredFestival: 'त्योहारी भोजन',
    elitePreferredCelebration: 'उत्सव / आयोजन भोजन',
    eliteDietaryNotes: 'आहार नोट्स (वैकल्पिक)',
    eliteDietaryNotesPlaceholder: 'जैसे शाकाहारी',
    eliteBrowseTitle: 'उपलब्ध विशेष आयोजन भोजन',
    eliteBrowseDesc: 'शादियों, त्योहारों और उत्सवों से भोजन। दूरी और दिशा देखने के लिए कार्ड पर क्लिक करें।',
    eliteDistanceAway: '{{km}} किमी दूर',
    eliteGetDirections: 'दिशा देखें',
    eliteNoEliteFoodsYet: 'अभी तक कोई विशेष आयोजन भोजन सूचीबद्ध नहीं।',

    clickForDetails: 'विवरण के लिए क्लिक करें',
    backToReport: 'रिपोर्ट पर वापस',
    detailedReport: 'विस्तृत रिपोर्ट',
    dailyBreakdown: 'दैनिक विवरण',
    weeklyBreakdown: 'साप्ताहिक विवरण',
    monthlyBreakdown: 'मासिक विवरण',
    topSources: 'शीर्ष स्रोत',
    trendAnalysis: 'यह चार्ट प्रत्येक दिन के लिए विस्तृत डेटा बिंदुओं के साथ साप्ताहिक प्रवृत्ति दिखाता है।',
    lastWeekSummary: 'पिछले सप्ताह निरंतर वृद्धि के साथ सुसंगत प्रदर्शन दिखाया।',
    lastMonthSummary: 'पिछले महीने ने प्रत्येक सप्ताह बढ़ते प्रभाव के साथ मजबूत वृद्धि का प्रदर्शन किया।',
    lastYearSummary: 'पिछले वर्ष ने निरंतर मासिक वृद्धि के साथ प्रगतिशील सुधार दिखाया।',

    adminOrgReport: 'संगठन रिपोर्ट',
    freshFoodAnalyser: 'ताजा भोजन विश्लेषक',
    postFood: 'भोजन पोस्ट करें',
    overallReport: 'समग्र रिपोर्ट',
    overallReportDesc: 'आपके संगठन के प्रभाव और गतिविधि का सारांश। विस्तृत विवरण के लिए एक कार्ड पर क्लिक करें।',
    peopleServed: 'लोगों को सेवा दी',
    mealsDelivered: 'भोजन वितरित',
    deliveriesCompleted: 'डिलीवरी पूरी',
    activeVolunteers: 'सक्रिय स्वयंसेवक',
    totalBeneficiaries: 'कुल लाभार्थी',
    successfulRuns: 'सफल रन',
    deliveries: 'डिलीवरी',
    volunteers: 'स्वयंसेवक',
    extendedBreakdown: 'विस्तृत विवरण',
    quarterToDate: 'त्रैमासिक से अब तक',
    yearToDate: 'वर्ष से अब तक',
    topLocation: 'शीर्ष स्थान',
    averagePerDelivery: 'प्रति डिलीवरी औसत',
    totalAllTime: 'कुल सभी समय',
    peakDayThisMonth: 'इस महीने का शीर्ष दिन',
    onTimeRate: 'समय पर दर',
    totalSuccessful: 'कुल सफल',
    avgDistancePerRun: 'प्रति रन औसत दूरी',
    newThisMonth: 'इस महीने नया',
    completed5PlusDeliveries: '5+ डिलीवरी पूरी',
    topVolunteerDeliveries: 'शीर्ष स्वयंसेवक (डिलीवरी)',
    totalActive: 'कुल सक्रिय',
    retentionRate: 'प्रतिधारण दर',
    equivalentEmissionsAvoided: 'समतुल्य उत्सर्जन से बचा',
    equivalentCarKm: 'समतुल्य कार किमी',
    equivalentTrees1Year: 'समतुल्य पेड़ (1 वर्ष)',
    foodRescued: 'बचाया गया भोजन',
    weightDivertedFromWaste: 'कचरे से हटाया गया वजन',
    primaryCategory: 'प्राथमिक श्रेणी',
    partnersInvolved: 'शामिल साझेदार',
    addFoodDonorsOnly: 'भोजन जोड़ें (केवल दानदाता)',
    addFoodDonorsDesc: 'दानदाता के रूप में, उस भोजन को जोड़ें जिसे पिकअप या डिलीवरी की आवश्यकता है। वैकल्पिक रूप से पहले हमारे AI चेकर के साथ ताजगी जांचें; फिर फॉर्म भरें। यह स्वयंसेवक पेज पर दिखाई देगा।',
    skipFillForm: 'छोड़ें → फॉर्म भरें',
    checkFreshnessFirstOptional: 'पहले ताजगी जांचें (वैकल्पिक)',
    foodNamePlaceholder: 'जैसे चावल और करी, ब्रेड रोल',
    type: 'प्रकार',
    foodType: 'भोजन का प्रकार',
    servings: 'सर्विंग',
    servingsPlaceholder: 'जैसे 10',
    addressPickupLocation: 'पता / पिकअप स्थान',
    addressPlaceholder: 'जैसे 123 मुख्य सड़क, चेन्नई',
    descriptionOptional: 'विवरण (वैकल्पिक)',
    descriptionPlaceholder: 'स्वयंसेवकों के लिए कोई नोट',
    adding: 'जोड़ रहा है…',
    addFood: 'भोजन जोड़ें',
    foodYouAddedVisibleToVolunteers: 'आपके द्वारा जोड़ा गया भोजन (स्वयंसेवकों को दिखाई देता है)',
    noFoodAddedYet: 'अभी तक कोई भोजन नहीं जोड़ा गया।',
    foodNameAndAddressRequired: 'भोजन का नाम और पता आवश्यक है।',
    foodAddedSuccess: 'भोजन जोड़ा गया। यह स्वयंसेवक पेज पर दिखाई देगा।',
    failedToAddFood: 'भोजन जोड़ने में विफल।',
    monthlyComparison: 'मासिक तुलना',
    thisMonthMeals: 'इस महीने (भोजन)',
    lastMonthMeals: 'पिछले महीने (भोजन)',
    vsLastMonth: 'पिछले महीने की तुलना में',
    impactTrends: 'प्रभाव रुझान',
    impactTrendsDesc: 'पिछले 6 महीनों में मासिक भोजन वितरित और लोगों को सेवा दी गई।',
    overviewAllTime: 'अवलोकन (सभी समय)',
    keyMetricsComparison: 'मुख्य मेट्रिक्स तुलना',
    foodType_meals: 'भोजन',
    foodType_vegetables: 'सब्जियां',
    foodType_baked: 'बेक किया हुआ',
    foodType_dairy: 'डेयरी',
    foodType_fruits: 'फल',
    foodType_others: 'अन्य',
    loading: 'लोड हो रहा है…',
    clearFreshnessResult: 'ताजगी परिणाम साफ करें',
    value: 'मूल्य',
    
    // Volunteer Mode
    volunteerMode: 'स्वयंसेवक मोड',
    volunteerModeDescription: 'संगठनों से उपलब्ध भोजन और आपके सौंपे गए डिलीवरी यहाँ देखें।',
    availableFoodFromDonors: 'दानदाताओं से उपलब्ध भोजन',
    availableFoodFromDonorsDesc: 'दानदाताओं द्वारा जोड़ा गया भोजन। स्वयंसेवक केवल देख सकते हैं और ताजगी की जांच कर सकते हैं।',
    noFoodFromDonors: 'अभी दानदाताओं से कोई भोजन नहीं है।',
    noFoodFromDonorsDesc: 'जब दानदाता भोजन जोड़ेंगे, तो यह यहाँ दिखाई देगा। आप प्रत्येक आइटम के लिए ताजगी की जांच कर सकते हैं।',
    myDeliveries: 'मेरी डिलीवरी',
    noDeliveriesAssigned: 'अभी तक कोई डिलीवरी असाइन नहीं की गई है।',
    noDeliveriesAssignedDesc: 'आपका संगठन आपको डिलीवरी असाइन करेगा।',
    status: 'स्थिति',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: React.ReactNode;
  /** When provided, language is controlled from parent (e.g. App) so all pages stay in sync */
  language?: Language;
  setLanguage?: (lang: Language) => void;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children, language: controlledLang, setLanguage: controlledSetLang }) => {
  const [internalLang, setInternalLang] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem('resqmeal_lang') as Language | null;
      return saved && ['en', 'ta', 'hi'].includes(saved) ? saved : 'en';
    } catch {
      return 'en';
    }
  });

  const language = controlledLang ?? internalLang;
  const setLanguage = controlledSetLang ?? setInternalLang;

  React.useEffect(() => {
    if (!controlledLang) return;
    try {
      localStorage.setItem('resqmeal_lang', language);
    } catch {}
  }, [language, controlledLang]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
